spring:
  datasource:
    url: jdbc:mysql://192.168.0.136:3306/nbu
    username: root
    password: root_123
    driver-class-name: com.mysql.cj.jdbc.Driver
keycloak:
  auth-server-url: http://192.168.0.138:8080/auth
  realm: dev
  ssl-required: external
  resource: my-app
  public-client: true
  use-resource-role-mappings: true
  security-constraints:
    - auth-roles:
        - user
      security-collections:
        - name: user
          patterns:
            - /*
